export const ErrorCodes = {
  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // Validation & Input
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',

  // Creator & Supporter
  CREATOR_NOT_FOUND: 'CREATOR_NOT_FOUND',
  SELF_SUPPORT_NOT_ALLOWED: 'SELF_SUPPORT_NOT_ALLOWED',
  CREATOR_NOT_ACTIVE: 'CREATOR_NOT_ACTIVE',
  KYC_REQUIRED: 'KYC_REQUIRED',

  // Material & Menu
  MATERIAL_NOT_FOUND: 'MATERIAL_NOT_FOUND',
  MATERIAL_INACTIVE: 'MATERIAL_INACTIVE',

  // Support & Pricing
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  PRICE_CALCULATION_FAILED: 'PRICE_CALCULATION_FAILED',

  // Payment
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
  PAYMENT_INITIALIZATION_FAILED: 'PAYMENT_INITIALIZATION_FAILED',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  WEBHOOK_VERIFICATION_FAILED: 'WEBHOOK_VERIFICATION_FAILED',

  // Ledger & Payout
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  PAYOUT_METHOD_REQUIRED: 'PAYOUT_METHOD_REQUIRED',
  PAYOUT_ALREADY_PROCESSED: 'PAYOUT_ALREADY_PROCESSED',

  // Content
  CONTENT_NOT_FOUND: 'CONTENT_NOT_FOUND',
  CONTENT_ACCESS_DENIED: 'CONTENT_ACCESS_DENIED',

  // System
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
