export const ErrorCodes = {
  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
  MOBILE_ACCESS_DENIED: 'MOBILE_ACCESS_DENIED',
  REGISTRATION_WEB_ONLY: 'REGISTRATION_WEB_ONLY',

  // Validation & Input
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',

  // Creator & Supporter
  CREATOR_NOT_FOUND: 'CREATOR_NOT_FOUND',
  SELF_SUPPORT_NOT_ALLOWED: 'SELF_SUPPORT_NOT_ALLOWED',
  CREATOR_NOT_ACTIVE: 'CREATOR_NOT_ACTIVE',
  KYC_REQUIRED: 'KYC_REQUIRED',

  // KYC
  KYC_ALREADY_VERIFIED: 'KYC_ALREADY_VERIFIED',
  KYC_UNDER_REVIEW: 'KYC_UNDER_REVIEW',
  KYC_SESSION_IN_PROGRESS: 'KYC_SESSION_IN_PROGRESS',
  KYC_ATTEMPT_LIMIT_REACHED: 'KYC_ATTEMPT_LIMIT_REACHED',
  KYC_PROVIDER_ERROR: 'KYC_PROVIDER_ERROR',
  KYC_SUBMISSION_NOT_FOUND: 'KYC_SUBMISSION_NOT_FOUND',
  KYC_INVALID_TRANSITION: 'KYC_INVALID_TRANSITION',
  KYC_BLOCKED: 'KYC_BLOCKED',
  KYC_UNAVAILABLE: 'KYC_UNAVAILABLE',

  // Material & Menu
  MATERIAL_NOT_FOUND: 'MATERIAL_NOT_FOUND',
  MATERIAL_INACTIVE: 'MATERIAL_INACTIVE',

  // Support & Pricing
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  PRICE_CALCULATION_FAILED: 'PRICE_CALCULATION_FAILED',

  // Payment
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
  PAYMENT_INITIALIZATION_FAILED: 'PAYMENT_INITIALIZATION_FAILED',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  WEBHOOK_VERIFICATION_FAILED: 'WEBHOOK_VERIFICATION_FAILED',

  // Ledger & Payout
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  PAYOUT_METHOD_REQUIRED: 'PAYOUT_METHOD_REQUIRED',
  PAYOUT_ALREADY_PROCESSED: 'PAYOUT_ALREADY_PROCESSED',

  // Content
  CONTENT_NOT_FOUND: 'CONTENT_NOT_FOUND',
  CONTENT_ACCESS_DENIED: 'CONTENT_ACCESS_DENIED',

  // Account & Settings
  BALANCE_NOT_ZERO: 'BALANCE_NOT_ZERO',
  PENDING_PAYOUTS_EXIST: 'PENDING_PAYOUTS_EXIST',
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  CANNOT_DISCONNECT_SOLE_METHOD: 'CANNOT_DISCONNECT_SOLE_METHOD',
  CANNOT_REVOKE_CURRENT_SESSION: 'CANNOT_REVOKE_CURRENT_SESSION',
  PROVIDER_NOT_CONNECTED: 'PROVIDER_NOT_CONNECTED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',

  // System
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
