export enum UserRole {
  SUPPORTER = 'SUPPORTER',
  CREATOR = 'CREATOR',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
  MODERATOR = 'MODERATOR',
  FINANCE = 'FINANCE',
  SUPPORT = 'SUPPORT',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  BANNED = 'BANNED',
  DEACTIVATED = 'DEACTIVATED',
}

export enum CreatorStatus {
  REGISTERED = 'REGISTERED',
  PROFILE_CREATED = 'PROFILE_CREATED',
  KYC_PENDING = 'KYC_PENDING',
  VERIFIED = 'VERIFIED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  BANNED = 'BANNED',
  DEACTIVATED = 'DEACTIVATED',
}

export enum KycStatus {
  NOT_SUBMITTED = 'NOT_SUBMITTED',
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
}

export enum SupportStatus {
  CREATED = 'CREATED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAID = 'PAID',
  COMPLETED = 'COMPLETED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  CHARGEBACK = 'CHARGEBACK',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  CHARGEBACK = 'CHARGEBACK',
}

export enum PaymentProviderName {
  PAYSTACK = 'PAYSTACK',
}

export enum AccountType {
  CREATOR = 'CREATOR',
  PLATFORM = 'PLATFORM',
}

export enum LedgerEntryType {
  SUPPORT_PAYMENT = 'SUPPORT_PAYMENT',
  PLATFORM_FEE = 'PLATFORM_FEE',
  PAYOUT_RESERVATION = 'PAYOUT_RESERVATION',
  PAYOUT_COMPLETED = 'PAYOUT_COMPLETED',
  PAYOUT_REVERSED = 'PAYOUT_REVERSED',
  REFUND = 'REFUND',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum LedgerDirection {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
}

export enum PayoutStatus {
  REQUESTED = 'REQUESTED',
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum PostVisibility {
  PUBLIC = 'PUBLIC',
  EXCLUSIVE = 'EXCLUSIVE',
}

export enum PostStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum ModerationStatus {
  CLEAN = 'CLEAN',
  FLAGGED = 'FLAGGED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  REMOVED = 'REMOVED',
}

export enum Currency {
  NGN = 'NGN',
}
